package net.minevn.minigames.quests

enum class QuestObjective {
	// COMMON OBJECTIVES
	ONLINE,
	PLAY,
	LOGIN,
	QUEST_POINTS_EARN,
	COLLECT_DROP,

	// BEDWARS
	BW_KILL,
	BW_WIN,
	BW_BEDDESTROY,

	// BUILD BATTLE
	BB_POINTS,
	BB_WIN,

	// MINESTRIKE
	MS_KILL,
	MS_WIN,
	MS_GAME_WIN,
	MS_ESCAPE_SUCCESS,
	MS_BOMB_DEFUSE,
	MS_BOMB_PLANT,
	MS_BOMB_PLANT_OR_DEFUSE,
	MS_INFECT,
	MS_ZOMBIE_SURVIVAL,
	MS_GATE_BREAK,
	MS_TOP_1,
	MS_LAST_SOLDIER,
	MS_DAILY_DONE,
	MS_BAT_KILL,
	MS_DEFUSE_SURVIVE,
	MS_DEFUSE_WIN_NOKILL,
	MS_STREAK_3,
	MS_ASSIST,
	MS_ZOMBIE_KILL_STREAK_3,
	MS_REVENGE,
	MS_KILL_FROM_THE_GRAVE,
	MS_FLAG_STOLEN,
	MS_QUEST_DONE,
	MS_CTF_THIEF_KILL,
	MS_MUTANT_SURVIVAL,
	MS_NINJA_DEFUSE,
	MS_NO_BUY_WIN_ALIVE,
	MS_SD_TOP123,
	MS_ESCAPE_END_BUTTON,
	MS_TWO_BIRDS_WITH_ONE_BULLET,
	MS_SECOND_TO_NONE,
	MS_MYTHICMOB_KILL,

	// MURDER MYSTERY
	MM_KILL,
	MM_WIN,
	MM_PICK_GOLD,
	MM_SCORE,

	// VILLAGE DEFENSE
	VD_KILL,
	VD_WIN,

	// WOOL WARS
	WW_WIN,
	WW_KILL,
	WW_TOP_KILL,
	WW_TOP_PLACE,
	WW_TOP_BREAK,

	// THE LAB
	TL_WIN,
}